/* Hydration / resumption + client navigation.
 *
 * Boot: host scans [data-cerco] roots, assigns node ids; for each root the
 * host writes [u32 name_len][name][u32 props_len][props] at the scratch base
 * and calls cerco_hydrate_root(i). The runtime looks up the component's mount
 * function (registered by generated code) and runs it against the existing
 * SSR DOM. No re-rendering of server HTML.
 *
 * Navigation: fetch the new page (server-rendered full HTML), swap only the
 * region between the cerco:page markers via the host's swap_page import —
 * the layout (header/nav/footer) sits outside the markers and survives.
 * Heap rewinds between pages so RAM stays bounded.
 */
#include "cerco_client.h"
#include "client_internal.h"
#include "wasm_libc.h"


/* generated by the build into sf_client.c / components_gen.c */
extern const cerco_component cerco_components_table[];
extern const uint32_t cerco_components_count;

static uint32_t read_u32(const uint8_t *p) {
  return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
         ((uint32_t)p[3] << 24);
}

static cerco_component *find_component(const char *name, size_t len) {
  for (uint32_t i = 0; i < cerco_components_count; i++) {
    const char *n = cerco_components_table[i].name;
    if (strlen(n) == len && memcmp(n, name, len) == 0) {
      return (cerco_component *)&cerco_components_table[i];
    }
  }
  return 0;
}

/* host -> wasm: hydrate root i (host staged name+props at scratch base) */
__attribute__((export_name("cerco_hydrate_root")))
void cerco_hydrate_root(int32_t index) {
  uint8_t *base = cerco_scratch_base();
  uint32_t name_len = read_u32(base);
  const char *name = (const char *)base + 4;
  if (name_len > 128) return;
  uint32_t props_len = read_u32(base + 4 + name_len);
  const char *props = (const char *)base + 4 + name_len + 4;
  if (4 + name_len + 4 + props_len > 65536u - 16u) return;
  cerco_component *c = find_component(name, name_len);
  /* advance scratch so mount-time allocations cannot clobber props */
  cerco_scratch_advance(4 + name_len + 4 + props_len);
  if (!c) return;
  c->mount(index, props);
  cerco_dom_flush();
}

/* host -> wasm: scan + hydrate everything (boot or after navigation) */
__attribute__((export_name("cerco_hydrate_all")))
void cerco_hydrate_all(void) { host_hydrate_roots(); }

/* ---------------------------------------------------------------- navigation */

static char g_current_path[512] = "/";

const char *cerco_current_path(void) { return g_current_path; }

static void nav_page_done(int status, const uint8_t *data, int32_t len, void *user);

void cerco_navigate(const char *path) {
  size_t n = strlen(path);
  if (n >= sizeof(g_current_path)) n = sizeof(g_current_path) - 1;
  memcpy(g_current_path, path, n);
  g_current_path[n] = 0;

  cerco_events_reset();
  cerco_roots_reset();
  cerco_heap_rewind();
  cerco_scratch_reset();

  cerco_http_get(path, nav_page_done, 0);
}

static void extract_between(const char *html, const char *start_marker,
                            const char *end_marker, size_t *out_off,
                            size_t *out_len) {
  const char *s = strstr(html, start_marker);
  if (!s) { *out_off = 0; *out_len = 0; return; }
  s += strlen(start_marker);
  const char *e = strstr(s, end_marker);
  if (!e) { *out_off = 0; *out_len = 0; return; }
  *out_off = (size_t)(s - html);
  *out_len = (size_t)(e - s);
}

static void nav_page_done(int status, const uint8_t *data, int32_t len, void *user) {
  (void)user;
  if (status != 200 || !data || len <= 0) {
    host_nav_reload(); /* fall back to full document load */
    return;
  }
  const char *html = (const char *)data;
  size_t off, plen;
  extract_between(html, "<!--cerco:page-->", "<!--cerco:/page-->", &off, &plen);
  if (!plen || plen > 60000u /* scratch is 64 KiB; title needs ~1 KiB */) {
    host_nav_reload(); /* fall back to full document load */
    return;
  }
  /* stage the region + NUL in scratch (the host reads it from wasm memory) */
  char *region = cerco_scratch_alloc(plen + 1);
  if (!region) {
    host_nav_reload();
    return;
  }
  memcpy(region, html + off, plen);
  region[plen] = 0;
  /* swap only the page region; markers missing -> full document load */
  if (!host_swap_page((int32_t)region, (int32_t)plen)) {
    host_nav_reload();
    return;
  }

  size_t toff = 0, tlen = 0;
  const char *t = strstr(html, "<title>");
  if (t) {
    t += 7;
    const char *te = strstr(t, "</title>");
    if (te && (size_t)(te - t) < 512) {
      toff = (size_t)(t - html);
      tlen = (size_t)(te - t);
    }
  }
  if (tlen) {
    char *title = cerco_scratch_alloc(tlen + 1);
    if (title) {
      memcpy(title, html + toff, tlen);
      title[tlen] = 0;
      host_set_title((int32_t)title, (int32_t)tlen);
    }
  }
  cerco_hydrate_all();
}

/* host -> wasm: browser navigated (link click / popstate); path at scratch */
__attribute__((export_name("cerco_navigate")))
void cerco_navigate_export(int32_t path_len) {
  char path[512];
  if (path_len <= 0 || path_len > (int32_t)sizeof(path) - 1) return;
  memcpy(path, cerco_scratch_base(), (size_t)path_len);
  path[path_len] = 0;
  cerco_scratch_reset();
  cerco_navigate(path);
}

/* host -> wasm: boot */
__attribute__((export_name("cerco_boot")))
void cerco_boot(void) {
  cerco_heap_init();
  cerco_scratch_reset();
  int32_t n = host_location((int32_t)g_current_path, (int32_t)sizeof(g_current_path) - 1);
  if (n < 0 || n > (int32_t)sizeof(g_current_path) - 1) n = 0;
  g_current_path[n] = 0;
  cerco_hydrate_all();
}
