/* generated by mkbundle — do not edit */
#ifndef CERCO_BUNDLE_H
#define CERCO_BUNDLE_H

#define CERCO_PLATFORM "darwin"
#define CERCO_ARCH "arm64"

typedef struct {
  const char *path;
  const unsigned char *data;
  unsigned int len;
} bundle_file;

extern const bundle_file cerco_bundle[73];
#define CERCO_BUNDLE_COUNT 73

#endif
