/* mkbundle — generates cli/bundle.h + cli/bundle.c embedding the SDK.
 * Usage: mkbundle <cerco-root> <platform> <arch> <libuv.a> <libllhttp.a>
 */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <dirent.h>

#define MAX_FILES 8192

typedef struct {
  char path[512]; /* bundle-relative path */
  char full[1024];
  long size;
} entry;

static entry files[MAX_FILES];
static int n_files = 0;

static void add_file(const char *rel, const char *full, long size) {
  if (n_files >= MAX_FILES) { fprintf(stderr, "too many files\n"); exit(1); }
  snprintf(files[n_files].path, sizeof(files[n_files].path), "%s", rel);
  snprintf(files[n_files].full, sizeof(files[n_files].full), "%s", full);
  files[n_files].size = size;
  n_files++;
}

static void scan_dir(const char *root, const char *prefix, const char *rel) {
  char full[1024];
  snprintf(full, sizeof(full), "%s/%s%s%s", root, prefix, rel[0] ? "/" : "", rel);
  DIR *d = opendir(full);
  if (!d) return;
  struct dirent *e;
  char relbuf[512], childfull[1024];
  while ((e = readdir(d))) {
    if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, "..")) continue;
    if (rel[0]) snprintf(relbuf, sizeof(relbuf), "%s/%s", rel, e->d_name);
    else snprintf(relbuf, sizeof(relbuf), "%s", e->d_name);
    snprintf(childfull, sizeof(childfull), "%s/%s/%s", root, prefix, relbuf);
    struct stat st;
    if (stat(childfull, &st) != 0) continue;
    if (S_ISDIR(st.st_mode)) {
      scan_dir(root, prefix, relbuf);
    } else if (S_ISREG(st.st_mode)) {
      char bundled[600];
      snprintf(bundled, sizeof(bundled), "%s/%s", prefix, relbuf);
      add_file(bundled, childfull, (long)st.st_size);
    }
  }
  closedir(d);
}

static void emit_file(FILE *out, int idx) {
  entry *f = &files[idx];
  FILE *in = fopen(f->full, "rb");
  if (!in) { fprintf(stderr, "cannot open %s\n", f->full); exit(1); }
  fprintf(out, "static const unsigned char bundle_data_%d[%ld] = {\n", idx, f->size);
  unsigned char buf[4096];
  long total = 0;
  size_t n;
  while ((n = fread(buf, 1, sizeof(buf), in)) > 0) {
    for (size_t i = 0; i < n; i++) {
      fprintf(out, "0%02o,", buf[i]);
      if (++total % 24 == 0) fprintf(out, "\n");
    }
  }
  fprintf(out, "\n};\n");
  fclose(in);
}

int main(int argc, char **argv) {
  if (argc != 6) {
    fprintf(stderr, "usage: %s <root> <platform> <arch> <libuv.a> <libllhttp.a>\n", argv[0]);
    return 1;
  }
  const char *root = argv[1];
  const char *platform = argv[2];
  const char *arch = argv[3];
  const char *libuv = argv[4];
  const char *libllhttp = argv[5];

  scan_dir(root, "include", "");
  scan_dir(root, "runtime", "");
  scan_dir(root, "templates", "");
  scan_dir(root, "vendor/llhttp/include", "");
  scan_dir(root, "vendor/libuv/include", "");
  add_file("lib/libuv.a", libuv, -1);
  add_file("lib/libllhttp.a", libllhttp, -1);

  /* fix sizes for the libs */
  for (int i = 0; i < n_files; i++) {
    if (files[i].size < 0) {
      struct stat st;
      if (stat(files[i].full, &st) == 0) files[i].size = (long)st.st_size;
    }
  }

  FILE *h = fopen("cli/bundle.h", "w");
  if (!h) { perror("bundle.h"); return 1; }
  fprintf(h,
      "/* generated by mkbundle — do not edit */\n"
      "#ifndef CERCO_BUNDLE_H\n"
      "#define CERCO_BUNDLE_H\n\n"
      "#define CERCO_PLATFORM \"%s\"\n"
      "#define CERCO_ARCH \"%s\"\n\n"
      "typedef struct {\n  const char *path;\n  const unsigned char *data;\n"
      "  unsigned int len;\n} bundle_file;\n\n"
      "extern const bundle_file cerco_bundle[%d];\n"
      "#define CERCO_BUNDLE_COUNT %d\n\n"
      "#endif\n", platform, arch, n_files, n_files);
  fclose(h);

  FILE *c = fopen("cli/bundle.c", "w");
  if (!c) { perror("bundle.c"); return 1; }
  fprintf(c, "/* generated by mkbundle — do not edit */\n");
  fprintf(c, "#include \"bundle.h\"\n\n");
  for (int i = 0; i < n_files; i++) {
    fprintf(c, "/* %s (%ld bytes) */\n", files[i].path, files[i].size);
    emit_file(c, i);
  }
  fprintf(c, "\nconst bundle_file cerco_bundle[%d] = {\n", n_files);
  for (int i = 0; i < n_files; i++) {
    fprintf(c, "  { \"%s\", bundle_data_%d, %ld },\n", files[i].path, i, files[i].size);
  }
  fprintf(c, "};\n");
  fclose(c);
  printf("bundle: %d files\n", n_files);
  return 0;
}
