/* cerco — client-side (wasm32) public API.
 *
 * The client runtime is freestanding wasm: no libc. The browser host (tiny
 * JS, generated by cerco) provides DOM/network via a handful of imports; all
 * DOM work flows through a command buffer flushed in batches.
 */
#ifndef CERCO_CLIENT_H
#define CERCO_CLIENT_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ memory */

/* allocate from the persistent heap (never freed; reset on navigation) */
void *cerco_alloc(size_t n);
/* duplicate string into persistent heap */
char *cerco_strdup(const char *s);
/* scratch arena: valid until the current event/batch completes */
void *cerco_scratch_alloc(size_t n);
char *cerco_scratch_strdup(const char *s);

/* ---------------------------------------------------------- string helpers */

/* The client is freestanding wasm: there is no libc to link against. The
 * runtime implements this subset and client components may use it freely. */
size_t strlen(const char *s);
int strcmp(const char *a, const char *b);
int strncmp(const char *a, const char *b, size_t n);
char *strstr(const char *haystack, const char *needle);
char *strcpy(char *dst, const char *src);
void *memcpy(void *dst, const void *src, size_t n);
void *memmove(void *dst, const void *src, size_t n);
void *memset(void *dst, int c, size_t n);
int memcmp(const void *a, const void *b, size_t n);

/* write v as decimal into buf; returns the length (buf needs 12 bytes) */
int32_t cerco_i32_to_str(char *buf, int32_t v);

/* truncating formatter, %s and %d/%i only (no printf in wasm). Always
 * NUL-terminates; returns the length written. */
int32_t cerco_format(char *buf, int32_t cap, const char *fmt, ...)
    __attribute__((format(printf, 3, 4)));

/* ----------------------------------------------------------------- signals */

typedef struct cerco_sig cerco_sig;

cerco_sig *cerco_signal_new(int32_t initial);
int32_t cerco_signal_get(cerco_sig *s);
void cerco_signal_set(cerco_sig *s, int32_t v);
int32_t cerco_signal_value(cerco_sig *s); /* read without tracking */

/* --------------------------------------------------------------------- dom */

/* querySelector scoped to a node; returns node id or 0 */
int32_t cerco_query(int32_t scope, const char *selector);
void cerco_set_text(int32_t node, const char *s);
void cerco_set_attr(int32_t node, const char *k, const char *v);
void cerco_remove_attr(int32_t node, const char *k);
void cerco_set_class(int32_t node, const char *cls);
void cerco_add_class(int32_t node, const char *cls);
void cerco_remove_class(int32_t node, const char *cls);
int32_t cerco_create(const char *tag, int32_t parent); /* returns new node id */
void cerco_remove(int32_t node);
void cerco_set_value(int32_t node, const char *v);
/* read an input's value; returns length or -1 */
int32_t cerco_value(int32_t node, char *buf, int32_t cap);
/* html set by trusted server response only (client navigation) */
void cerco_set_inner_html(int32_t node, const char *html);

/* ------------------------------------------------------------------ events */

typedef void (*cerco_ev_fn)(int32_t node, void *user);
void cerco_on(int32_t node, const char *event, cerco_ev_fn fn, void *user);

/* ---------------------------------------------------------------- bindings */

/* keep node.textContent == signal value */
void cerco_bind_text(int32_t node, cerco_sig *s);
/* toggle class presence based on bool signal */
void cerco_bind_class(int32_t node, cerco_sig *s, const char *cls);

/* -------------------------------------------------------------------- http */

/* Transport-level statuses, distinct from any HTTP code. */
#define CERCO_HTTP_FAILED     0  /* network error, CORS rejection, aborted */
#define CERCO_HTTP_TOO_LARGE (-1) /* body over the response cap; nothing read */

/* The callback receives the whole body or nothing — a response that does not
 * fit is reported as CERCO_HTTP_TOO_LARGE rather than silently truncated.
 * data is NUL-terminated one byte past len, so a text body can be handed
 * straight to strstr and friends. It is valid only for the duration of the
 * callback: copy anything you keep. */
typedef void (*cerco_http_cb)(int status, const uint8_t *data, int32_t len,
                              void *user);
void cerco_http_post(const char *url, const uint8_t *body, int32_t len,
                     cerco_http_cb cb, void *user);
void cerco_http_get(const char *url, cerco_http_cb cb, void *user);

/* ---------------------------------------------------------- navigation */

/* client-side navigation (fetch + content swap + re-hydrate) */
void cerco_navigate(const char *path);
/* current path tracked by the client router */
const char *cerco_current_path(void);
/* log to the browser console (debug) */
void cerco_debug_log(const char *s);

/* ------------------------------------------------------- server functions */

/* Callbacks receive the decoded result plus an error string (NULL on
 * success). String/bytes results point into a fetch buffer valid only for
 * the duration of the callback: copy them if you need to keep them. */
typedef void (*cerco_sf_cb_i32)(int32_t result, const char *error, void *user);
typedef void (*cerco_sf_cb_i64)(int64_t result, const char *error, void *user);
typedef void (*cerco_sf_cb_f64)(double result, const char *error, void *user);
typedef void (*cerco_sf_cb_str)(const char *result, const char *error, void *user);
typedef void (*cerco_sf_cb_bytes)(const uint8_t *data, int32_t len,
                                  const char *error, void *user);

/* builder used by generated stubs */
void cerco_sf_begin(uint32_t id, uint32_t nargs);
void cerco_sf_arg_i32(int32_t v);
void cerco_sf_arg_bool(int32_t v);
void cerco_sf_arg_i64(int64_t v);
void cerco_sf_arg_f64(double v);
void cerco_sf_arg_str(const char *s);
void cerco_sf_arg_bytes(const uint8_t *d, int32_t len);
void cerco_sf_submit_raw(void *cb, void *user, uint8_t want_type);

static inline void cerco_sf_submit_i32(void *cb, void *user) {
  cerco_sf_submit_raw(cb, user, 0);
}
static inline void cerco_sf_submit_bool(void *cb, void *user) {
  cerco_sf_submit_raw(cb, user, 3);
}
static inline void cerco_sf_submit_i64(void *cb, void *user) {
  cerco_sf_submit_raw(cb, user, 1);
}
static inline void cerco_sf_submit_f64(void *cb, void *user) {
  cerco_sf_submit_raw(cb, user, 2);
}
static inline void cerco_sf_submit_str(void *cb, void *user) {
  cerco_sf_submit_raw(cb, user, 4);
}
static inline void cerco_sf_submit_bytes(void *cb, void *user) {
  cerco_sf_submit_raw(cb, user, 5);
}

/* ------------------------------------------------------- hydration (hooks) */

/* id of hydration root i (host-assigned), or 0 */
int32_t cerco_root_node(int32_t index);

/* tiny json helpers for component props */
int32_t cerco_json_int(const char *json, const char *key, int32_t dflt);
/* extracts a string field into buf (NUL-terminated); returns 1 on success */
int cerco_json_str(const char *json, const char *key, char *buf, int32_t cap);

/* ------------------------------------------------------ component def macro */

typedef void (*cerco_mount_fn)(int32_t root, const char *props);
typedef struct {
  const char *name;
  cerco_mount_fn mount;
} cerco_component;

#define CERCO_CLIENT_COMPONENT(name)                                          \
  void cerco_component_##name(int32_t cerco_root, const char *cerco_props);   \
  void cerco_component_##name(int32_t cerco_root, const char *cerco_props)

#ifdef __cplusplus
}
#endif

#endif
